# Generated by Django 6.0.6 on 2026-06-07 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('ai_depth', models.IntegerField()),
                ('elo_before', models.IntegerField()),
                ('elo_after', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_s', models.IntegerField(default=0)),
                ('player_score', models.IntegerField(default=0)),
                ('ai_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
